### ISSUE TITLE
NNZ (Sparse) turn to 0 on Quantizing

### ISSUE THREAD

**Issue by dabadee** [NervanaSystems/distiller#115]
I am doing the following
1. Train simplenet on cifar
`python3 compress_classifier.py --arch simplenet_cifar ../../../data.cifar10 -p 30 -j=1 --lr=0.01 --epochs 100`

2. Prune using AGP
`python3 compress_classifier.py -a simplenet_cifar ../../../data.cifar10 -p 30 -j=1 --lr=0.01 --compress=agp_simplenet75.yaml --resume logs/2019.01.01-134735/checkpoint.pth.tar --epochs 25`

3. Quantize using QuantAwareTrainRangeLinearQuantizer
`python3 compress_classifier.py -a simplenet_cifar ../../../data.cifar10 -p 30 -j=1 --lr=0.001 --compress=quant.yaml --resume logs/2019.01.01-183251/checkpoint.pth.tar --epochs 20`

On the very first step both conv layers' weights and their associated float_weight, scale, and zero point layers become 100% sparse with 0 NNZ sparse values.

Is it a bug or am I going in wrong direction ?

My yaml files are as follows

**agp_simplenet75.yaml**
```
version: 1
pruners:
  fc1_pruner:
    class: 'AutomatedGradualPruner'
    initial_sparsity : 0.05
    final_sparsity: 0.75
    weights: ['module.fc1.weight']

  fc2_pruner:
    class: 'AutomatedGradualPruner'
    initial_sparsity : 0.05
    final_sparsity: 0.75
    weights: ['module.fc2.weight']
 
  fc3_pruner:
    class: 'AutomatedGradualPruner'
    initial_sparsity : 0.05
    final_sparsity: 0.75
    weights: ['module.fc3.weight']

  conv1_pruner:
    class: 'AutomatedGradualPruner'
    initial_sparsity : 0.03
    final_sparsity: 0.75
    weights: ['module.conv1.weight']

  conv2_pruner:
    class: 'AutomatedGradualPruner'
    initial_sparsity : 0.03
    final_sparsity: 0.75
    weights: ['module.conv2.weight']


lr_schedulers:
  # Learning rate decay scheduler
   pruning_lr:
     class: ExponentialLR
     gamma: 0.9


policies:
  - pruner:
      instance_name : 'conv1_pruner'
    starting_epoch: 100
    ending_epoch: 110
    frequency: 2

  - pruner:
      instance_name : 'conv2_pruner'
    starting_epoch: 100
    ending_epoch: 110
    frequency: 2

  - pruner:
      instance_name : 'fc1_pruner'
    starting_epoch: 100
    ending_epoch: 120
    frequency: 2

  - pruner:
      instance_name : 'fc2_pruner'
    starting_epoch: 100
    ending_epoch: 120
    frequency: 2

  - pruner:
      instance_name: 'fc3_pruner'
    starting_epoch: 100
    ending_epoch: 120
    frequency: 2

  - lr_scheduler:
      instance_name: pruning_lr
    starting_epoch: 101
    ending_epoch: 180
    frequency: 1
```
 **quant.yaml**
```
quantizers:
  linear_quantizer:
    class: QuantAwareTrainRangeLinearQuantizer
    bits_activations: 8
    bits_weights: 8
    mode: 'ASYMMETRIC_UNSIGNED'  # Can try "SYMMETRIC" as well
    ema_decay: 0.999   # Decay value for exponential moving average tracking of activation ranges
    per_channel_wts: True

policies:
    - quantizer:
        instance_name: linear_quantizer
      # For now putting a large range here, which should cover both training from scratch or resuming from some
      # pre-trained checkpoint at some unknown epoch
      starting_epoch: 0
      ending_epoch: 300
      frequency: 1
```
