### ISSUE TITLE
Total sparsity: 0.00

### ISSUE THREAD

**Issue by saturdays** [NervanaSystems/distiller#128]
I use below config to prune a senet model. But afte one epoch, I got this message:
**Total sparsity: 0.00**
What does't this mean?

```
version: 1
pruners:
  pruner2:
    class: 'SensitivityPruner'
    sensitivities:
      'module.features.layer2.0.conv1.weight': 0.25
      'module.features.layer2.0.conv2.weight': 0.25
      'module.features.layer2.0.conv3.weight': 0.25
      'module.features.layer2.1.conv1.weight': 0.25
      'module.features.layer2.1.conv2.weight': 0.25
      'module.features.layer2.1.conv3.weight': 0.25
      'module.features.layer2.2.conv1.weight': 0.25
      'module.features.layer2.2.conv2.weight': 0.25
      'module.features.layer2.2.conv3.weight': 0.25
lr_schedulers:
   pruning_lr:
     class: ExponentialLR
     gamma: 0.9

policies:
  - pruner:
      instance_name : 'pruner2'
    starting_epoch: 0
    ending_epoch: 38
    frequency: 2
  - lr_scheduler:
      instance_name: pruning_lr
    starting_epoch: 20
    ending_epoch: 40
    frequency: 1
```
