### ISSUE TITLE
Quantizing Layers Individually

### ISSUE THREAD

**Issue by dabadee** [NervanaSystems/distiller#146]
I am trying to quantize layers individually by mentioning layers in the schedule, but it just quantizes all the layers using the last defined quantizer.

Does distiller support quantizing different layers to a different level ?
```
quantizers:
  linear_quantizer:
    class: QuantAwareTrainRangeLinearQuantizer
    bits_activations: 5
    bits_weights: 5
    mode: 'ASYMMETRIC_UNSIGNED'  # Can try "SYMMETRIC" as well
    ema_decay: 0.999   # Decay value for exponential moving average tracking of activation ranges
    per_channel_wts: True
    weights: ['module.fc1.weight']
      
    linear_quantizer2:
    class: QuantAwareTrainRangeLinearQuantizer
    bits_activations: 8
    bits_weights: 8
    mode: 'ASYMMETRIC_UNSIGNED'  # Can try "SYMMETRIC" as well
    ema_decay: 0.999   # Decay value for exponential moving average tracking of activation ranges
    per_channel_wts: True
    weights: ['module.fc2.weight']

policies:
    - quantizer:
        instance_name: linear_quantizer
      # For now putting a large range here, which should cover both training from scratch or resuming from some
      # pre-trained checkpoint at some unknown epoch
      starting_epoch: 0
      ending_epoch: 500
      frequency: 1
        
     - quantizer:
        instance_name: linear_quantizer2
      # For now putting a large range here, which should cover both training from scratch or resuming from some
      # pre-trained checkpoint at some unknown epoch
      starting_epoch: 0
      ending_epoch: 500
      frequency: 1    
```

**Comment by guyjacob** [comment]
It seems you're trying to define the quantizers the same way you'd define pruners / regularizers, but it's done a bit differently.
Please take a look here:
https://nervanasystems.github.io/distiller/schedule/index.html#quantization
As you'll see - to get different bit-widths for different layers, you don't define separate quantizers. You define a single quantizer, with a default setting for # of bits, and then you can override that for specific layers with the `bits_overrides` section. You can specify specific layer names or use regular-expressions. Also, there's no need to specify the `module.` prefix (that's the result of using `DataParallel` to wrap the model) or the `.weight` suffix. Just the actual module/layer name.

(P.S. defining more than one quantizer should raise an error, so it's odd that it just takes the last one as you say. Will check that out)

**Comment by guyjacob** [comment]
For your specific case, if you're looking to quantize just those specific layers and no others, you'd define something like:

```
quantizers:
  linear_quantizer:
    class: QuantAwareTrainRangeLinearQuantizer
    bits_activations: null
    bits_weights: null
    mode: 'ASYMMETRIC_UNSIGNED'  # Can try "SYMMETRIC" as well
    ema_decay: 0.999   # Decay value for exponential moving average tracking of activation ranges
    per_channel_wts: True
    bits_overrides:
        fc1:
            wts: 5
            acts: 5
        fc2:
            wts: 8
            acts: 8

policies:
    - quantizer:
        instance_name: linear_quantizer
      # For now putting a large range here, which should cover both training from scratch or resuming from some
      # pre-trained checkpoint at some unknown epoch
      starting_epoch: 0
      ending_epoch: 500
      frequency: 1
```

Note that I specified `null` for the top-level `bits_activations/weights`. That means that by default nothing is quantized. And then you can override for the specific layers.
