### ISSUE TITLE
This sample YAML has wrong description?

### ISSUE THREAD

**Issue by eduidl** [NervanaSystems/distiller#191]
This issue is about https://github.com/NervanaSystems/distiller/blob/master/examples/quantization/quant_aware_train/preact_resnet20_cifar_pact.yaml#L44

```yaml
lr_schedulers:
  training_lr:
    class: MultiStepLR
    milestones: [60, 120]
    gammas: 0.1

```

PyTorch's `MultiStepLR` class requires `gamma` not `gammas`. I suppose `gamma` is corrent, which is wrong?

reference: https://pytorch.org/docs/stable/optim.html#torch.optim.lr_scheduler.MultiStepLR

Regards.
