### ISSUE TITLE
Network Thinning Issue on Resnet20 CIFAR10

### ISSUE THREAD

**Issue by dabadee** [NervanaSystems/distiller#304]
I am using the following schedule

```
version: 1
pruners:
  filter_pruner:
    class: 'L1RankedStructureParameterPruner'
    group_type: Filters
    desired_sparsity: 0.5
    weights: ['module.layer1.0.conv2.weight']
extensions:
  net_thinner:
    class: FilterRemover
    thinning_func_str: remove_filters
    arch: 'resnet20_cifar'
    dataset: 'cifar10'
policies:
  - pruner:
      instance_name : 'filter_pruner'
    epochs: [0]
  - extension:
      instance_name : 'net_thinner'
    epochs: [0]
```

and get the following error

```
RuntimeError: The size of tensor a (8) must match the size of tensor b (16) at non-singleton dimension 1
```

Can anyone suggest a quick fix

Thanks
