### ISSUE TITLE
prune conv filters will not process successor bn layers

### ISSUE THREAD

**Issue by Jie-Fang** [NervanaSystems/distiller#36]
I meet a problem when i run the **pruning_filters_for_efficient_convnets** example which uses **resnet56_cifar_filter_rank.yaml**. One mistake i find is outdated document described this yaml. On the document website, it writes:

```
extensions:
  net_thinner:
      class: 'ResnetCifarFilterRemover'
      thinning_func_str: resnet_cifar_remove_filters
```
but in the yaml file, it use:
```
extensions:
  net_thinner:
      class: 'FilterRemover'
      thinning_func_str: remove_filters
      arch: 'resnet56_cifar'
      dataset: 'cifar10'
```

The net_thinner is different. There are no `ResnetCifarFilterRemover` class and `resnet_cifar_remove_filters` in the source code.

The biggest problem is the example cant work. I find when a conv layer remove some filters, it will not change the following bn layer. The error is below:

```
RuntimeError: running_mean should contain 7 elements not 16
```

I debug the code, it seems `create_thinning_recipe_filters` function in the thinning.py exists some bugs, it won't handle bn layers. [the line to handle bn layers](https://github.com/NervanaSystems/distiller/blob/master/distiller/thinning.py#L351)
