### ISSUE TITLE
Questions on invoking quantization aware training from full-precision checkpoints

### ISSUE THREAD

**Issue by lehahoang** [NervanaSystems/distiller#408]
Hi,

In this post, I would like to raise a few questions:
1. How can we justify if quantization-aware training from full-precision checkpoints gives us the correct result?
2. How do we capture quantized weights during the quantization-aware training process?
3. Are weights quantized on-the-fly by using the module quantize_wts in this [tutorial](https://nervanasystems.github.io/distiller/quantization.html) without being temporarily saved?
Here is my experimental setup:
- A full-precision VGG-16 on CIFAR-10 dataset with 88.81% top-1 accuracy
- A quantization.yaml file:
```
quantizers:
  linear_quantizer:
    class: QuantAwareTrainRangeLinearQuantizer
    bits_activations: 8
    bits_weights: 8
    mode: 'SYMMETRIC'  # Can try "SYMMETRIC" as well
    per_channel_wts: True

policies:
    - quantizer:
        instance_name: linear_quantizer
      starting_epoch: 0
      ending_epoch: 100
      frequency: 1
```
- 5000 samples of validation dataset
- My command line, which is inspired from [here](https://github.com/NervanaSystems/distiller/pull/309), is:

`CUDA_VISIBLE_DEVICES=1 python compress_classifier.py -a vgg16_cifar --lr 0.001 ./data.cifar --epochs 91 --compress=vgg16/quant.yaml --wd=0.0001 --vs=0.1 --resume-from vgg16/checkpoint.pth.tar --deterministic `

My assumption in post-training quantization is that weights are quantized by using wrapper_module then are forwarded to the network. This is not an issue of capturing quantized weights during the process. Regarding quantization-aware training, weights are quantized magically "somewhere" in the process. Therefore, I am not sure if my command line invoked weights to be quantized. Please correct me if I am wrong. 

Thank you.
