### ISSUE TITLE
question about post-training quantization and sparsity

### ISSUE THREAD

**Issue by cindybrain** [NervanaSystems/distiller#448]
I have three questions:

- Question1: I use the .yaml file 1(hs_vgg16_quant_post_train.yaml):
```
quantizers:
  post_train_quantizer:
    class: PostTrainLinearQuantizer
    bits_activations: 6
    bits_parameters: 6
    bits_accum: 32
    mode: ASYMMETRIC_UNSIGNED
    model_activation_stats: ../quantization/post_train_quant/stats/hs_vgg16_quant_stats.yaml
    per_channel_wts: True
    clip_acts: AVG
```

and the .yaml file 2:
```
quantizers:
  post_train_quantizer:
    class: PostTrainLinearQuantizer
    bits_activations: 6
    bits_parameters: 6
    bits_accum: 32
    mode: ASYMMETRIC_UNSIGNED
    model_activation_stats: ../quantization/post_train_quant/stats/hs_vgg16_quant_stats.yaml
    per_channel_wts: True
    clip_acts: AVG
    overrides:
      conv1:
        bits_weights: 8
        bits_activations: 8
      .*add:
        bits_weights: 8
        bits_activations: 8
      fc:
        bits_weights: 8
        bits_activations: 8
        clip_acts: NONE
```
run the following command-line:
```
python compress_classifier.py -a vgg16_cifar -p 10 -j 22 ../../../data.cifar10 --resume-from=./logs/vgg16-sparse-1/checkpoint.pth.tar --evaluate --quantize-eval --qe-config-file ../quantization/post_train_quant/hs_vgg16_quant_post_train.yaml
```
I get the same log file and same output, It sames that the overrides function don't work, I don't know what's wrong with it.
```
Updated stats saved to logs/2019.12.19-120548/quant_stats_after_prepare_model.yaml
Parameter 'features.module.0.wrapped_module.weight' will be quantized to 6 bits
Parameter 'features.module.0.wrapped_module.bias' will be quantized to 32 bits
Parameter 'features.module.2.wrapped_module.weight' will be quantized to 6 bits
Parameter 'features.module.2.wrapped_module.bias' will be quantized to 32 bits
Parameter 'features.module.5.wrapped_module.weight' will be quantized to 6 bits
Parameter 'features.module.5.wrapped_module.bias' will be quantized to 32 bits
Parameter 'features.module.7.wrapped_module.weight' will be quantized to 6 bits
Parameter 'features.module.7.wrapped_module.bias' will be quantized to 32 bits
Parameter 'features.module.10.wrapped_module.weight' will be quantized to 6 bits
Parameter 'features.module.10.wrapped_module.bias' will be quantized to 32 bits
Parameter 'features.module.12.wrapped_module.weight' will be quantized to 6 bits
Parameter 'features.module.12.wrapped_module.bias' will be quantized to 32 bits
Parameter 'features.module.14.wrapped_module.weight' will be quantized to 6 bits
Parameter 'features.module.14.wrapped_module.bias' will be quantized to 32 bits
Parameter 'features.module.17.wrapped_module.weight' will be quantized to 6 bits
Parameter 'features.module.17.wrapped_module.bias' will be quantized to 32 bits
Parameter 'features.module.19.wrapped_module.weight' will be quantized to 6 bits
Parameter 'features.module.19.wrapped_module.bias' will be quantized to 32 bits
Parameter 'features.module.21.wrapped_module.weight' will be quantized to 6 bits
Parameter 'features.module.21.wrapped_module.bias' will be quantized to 32 bits
Parameter 'features.module.24.wrapped_module.weight' will be quantized to 6 bits
Parameter 'features.module.24.wrapped_module.bias' will be quantized to 32 bits
Parameter 'features.module.26.wrapped_module.weight' will be quantized to 6 bits
Parameter 'features.module.26.wrapped_module.bias' will be quantized to 32 bits
Parameter 'features.module.28.wrapped_module.weight' will be quantized to 6 bits
Parameter 'features.module.28.wrapped_module.bias' will be quantized to 32 bits
Parameter 'classifier.wrapped_module.weight' will be quantized to 6 bits
Parameter 'classifier.wrapped_module.bias' will be quantized to 32 bits
```

-  Question2: I know that
>Distiller only simulates post-training quantization ......... the way post-training quantization is implemented, supported layers are wrapped with quantize/de-quantizer operations, but the layers themselves are unchanged. They still operate on FP32 tensors, but these tensors are restricted to contain only integer value

but I use the quantilization, and the checkpoint file become smaller. I don't understant why the checkpoint file can become smaller since that the value is represented by FP32?  Does it mean the weight value is stored in the checkpoint file as integer?

- Question 3: The last question is not related to the quatization but about the sparsity. when I use  
```
extensions:
  net_thinner:
      class: 'FilterRemover'
      thinning_func_str: remove_filters
      arch: 'resnet20_cifar'
      dataset: 'cifar10'
```
and
``` 
 - extension:
      instance_name: net_thinner
    epochs: [30]
```
the sparsity becomes zero at epoch  30, and increases from scratch in the following epochs, so the final sparsity is not the "total sparsity". How can I get the true "total sparsity" at the end of the pruning process?

I hope that someone could help me :)
