### ISSUE TITLE
How to change quantizer parameters during training?

### ISSUE THREAD

**Issue by retaw106** [NervanaSystems/distiller#476]
Fow example, the example 'quant_aware_train_linear_quant.yaml' uses a constant quantizer:
```
quantizers:
  linear_quantizer:
    class: QuantAwareTrainRangeLinearQuantizer
    bits_activations: 8
    bits_weights: 8
    mode: 'ASYMMETRIC_UNSIGNED'  # Can try "SYMMETRIC" as well
    ema_decay: 0.999   # Decay value for exponential moving average tracking of activation ranges
    per_channel_wts: True

policies:
    - quantizer:
        instance_name: linear_quantizer
      # For now putting a large range here, which should cover both training from scratch or resuming from some
      # pre-trained checkpoint at some unknown epoch
      starting_epoch: 0
      ending_epoch: 300
      frequency: 1
```
If I want to gradually decrease the quantization bits, I think I can change it like this:
```
quantizers:
  linear_quantizer1:
    class: QuantAwareTrainRangeLinearQuantizer
    bits_activations: 9
    bits_weights: 9
    mode: 'ASYMMETRIC_UNSIGNED'  # Can try "SYMMETRIC" as well
    ema_decay: 0.999   # Decay value for exponential moving average tracking of activation ranges
    per_channel_wts: True
  linear_quantizer2:
    class: QuantAwareTrainRangeLinearQuantizer
    bits_activations: 8
    bits_weights: 8
    mode: 'ASYMMETRIC_UNSIGNED'  # Can try "SYMMETRIC" as well
    ema_decay: 0.999   # Decay value for exponential moving average tracking of activation ranges
    per_channel_wts: True

...

policies:
    - quantizer:
        instance_name: linear_quantizer1
      # For now putting a large range here, which should cover both training from scratch or resuming from some
      # pre-trained checkpoint at some unknown epoch
      starting_epoch: 0
      ending_epoch: 10
      frequency: 1
    - quantizer:
        instance_name: linear_quantizer2
      # For now putting a large range here, which should cover both training from scratch or resuming from some
      # pre-trained checkpoint at some unknown epoch
      starting_epoch: 11
      ending_epoch: 20
      frequency: 1
...
```
Is it correct?
This method would be very cumbersome when the changing schedule becomes longer (e.g. quantize_bit = 20-epoch).
So is there any better suggestions?

**Comment by guyjacob** [comment]
What you did will not work. If I'm not mistaken this will actually raise an error, since we don't allow more than one quantizer to be configured.

The functionality you're looking for isn't supported as-is.

It's a bit tricky because weights quantization during training is controlled by the Quantizer (not as part of the model's `forward` call), while activations are quantized via dedicated modules that are inserted by the Quantizer (which are invoked during `forward`).

Here's a sketch of how you could implement something like this. I haven't tested it, but something along these lines should work. I'm subclassing the existing quantizer and adding the new functionality.

```python
from distiller.quantization import QuantAwareTrainRangeLinearQuantizer
from distiller.quantization.range_linear import FakeLinearQuantization

class BitWidthScheduleQAT(QuantAwareTrainRangeLinearQuantizer):
    def __init__(self, model, optimizer=None, bits_activations=32, bits_weights=32,
                 bits_bias=32, overrides=None, mode='SYMMETRIC', ema_decay=0.999,
                 per_channel_wts=False, quantize_inputs=True, num_bits_inputs=None,
                 bw_schedule=None):
        super(BitWidthScheduleQAT, self).__init__(
            model, optimizer, bits_activations, bits_weights, bits_bias, overrides,
            mode, ema_decay, per_channel_wts, quantize_inputs, num_bits_inputs
        )
        self.bw_schedule = {} or bw_schedule

    def update_bit_widths(self, epoch, iteration):
        # Get/calculate new bit-width based on bw_schedule and/or epoch number
        # and/or iteration. Here I assume bw_schedule is a dict with epoch number
        # as key
        if epoch in self.bw_schedule:
            new_bits_acts = self.bw_schedule[epoch]['bits_activations']
            new_bits_wts = self.bw_schedule[epoch]['bits_weights']

            # This is the code that actually modifies the bit-widths

            # Weights quantization is handled by the Quantizer itself
            for param_metadata in self.params_to_quantize:
                param_metadata.num_bits = new_bits_wts

            # Activations quantization is handled within the fake-quant
            # modules inserted by Quantizer
            for name, module in self.model.named_modules():
                if isinstance(module, FakeLinearQuantization):
                    module.num_bits = new_bits_acts
```
You could call the `update_bbit_widths` function from the [`QuantizationPolicy`](https://github.com/NervanaSystems/distiller/blob/2291fdcc2ea642a98d4e20629acb5a9e2e04b4e6/distiller/policy.py#L317). You can implement the `on_minibatch_begin` function:
```python
def on_minibatch_begin(self, model, epoch, minibatch_id, minibatches_per_epoch,
                       zeros_mask_dict, meta, optimizer=None):
    if isinstance(self.quantizer, BitWidthScheduleQAT):
        self.quantizer.update_bit_widths(epoch, minibatch_id)
```
Or if you want it only at the epoch level, implement the `on_epoch_end` or `on_epoch_begin` functions.

Finally - notice the `bw_schedule` I added as the last argument for `BitWidthScheduleQAT`. You can use that in your YAML schedule, and Distiller will automatically detect that and pass it to the Quantizer instance. In the code above I assumed this argument is a dict with epoch number as key. So to get the same effect that you tried to get in your question, you could do this:
```yaml
quantizers:
  linear_quantizer:
    class: BitWidthScheduleQAT
    bits_activations: 9
    bits_weights: 9
    mode: 'ASYMMETRIC_UNSIGNED'
    ema_decay: 0.999
    per_channel_wts: True
    bw_schedule:
        10:
            bits_activations: 8
            bits_weights: 8

policies:
    - quantizer:
        instance_name: linear_quantizer
      starting_epoch: 0
      ending_epoch: 300
      frequency: 1
```
Note that I made `bw_schedule` a dict only for the sake of example, to show how we add an argument and then define it in the YAML. You could, as another option, make it a string that you'll use to choose from one or more pre-defined scheduling functions (e.g. 20-epoch like you mentioned above). Basically it can be any built-in python you want...
